[server]
headless = true
runOnSave = true
port = 8501
showDeployButton = false


[theme]
base = "dark"         # Options: "light" or "dark"
primaryColor = "#2e86de"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#212529"
font = "sans serif"    # Options: "sans serif", "serif", "monospace"

